# permissions for end users to edit echoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hakjun-operator
    app.kubernetes.io/managed-by: kustomize
  name: echo-editor-role
rules:
- apiGroups:
  - app.junkmm.site
  resources:
  - echoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.junkmm.site
  resources:
  - echoes/status
  verbs:
  - get
